# Generated by Django 2.2 on 2020-07-23 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=140)),
                ('dob', models.DateField(default='NA', error_messages={1: 'Enter Valid Information'}, help_text='Enter in DD/MM/YYYY Format')),
                ('placeOfBirth', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=140)),
                ('gender', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=7)),
                ('address', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=255)),
                ('city', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=72)),
                ('country', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=72)),
                ('zipcode', models.IntegerField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=10)),
                ('email', models.EmailField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=254)),
                ('aadhar', models.IntegerField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=12, unique=True)),
                ('pancard', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=10, unique=True)),
                ('passport', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=14, unique=True)),
                ('dlicense', models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=14, unique=True)),
                ('height', models.IntegerField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=3)),
                ('unique_feature', models.TextField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=255)),
                ('prev_records', models.CharField(default='NA', max_length=1000)),
            ],
        ),
    ]
