# Generated by Django 2.2 on 2020-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='aadhar',
            field=models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=12, unique=True),
        ),
    ]
