# Generated by Django 2.2 on 2020-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200728_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='height',
            field=models.CharField(blank=True, default='', error_messages={1: 'Enter Valid Information'}, max_length=3),
        ),
    ]
