# Generated by Django 2.2 on 2020-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200723_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='zipcode',
            field=models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=10),
        ),
    ]
