# Generated by Django 2.2 on 2020-07-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(default='NA', error_messages={1: 'Enter Valid Information'}, max_length=140),
        ),
    ]
